version: '3'

volumes:
  prometheus-data:
    driver: local
  grafana-data:
    driver: local

services:

  prometheus:
    build: 
      context: ./pormetheus
    container_name: prometheus
    ports: 
      - "9090:9090" #not encrypted
    volumes:
      - prometheus-data:/prometheus
    restart: unless-stopped
    command: "--config.file=/config/prometheus.yaml"

  grafana:
    build: 
      context: ./grafana
    container_name: grafana
    environment:
      - GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
      - GF_SERVER_DOMAIN=sysad-project.zany.ch
      - GF_SERVER_ROOT_URL="%(protocol)s://%(domain)s:%(http_port)s/grafana/"
      - GF_SERVE_FROM_SUB_PATH=ture
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    restart: unless-stopped