FROM  docker.io/nextcloud:25.0.2-apache

RUN apt update  && export DEBIAN_FRONTEND=noninteractive \
 && apt -y install --no-install-recommends ssl-cert
RUN a2enmod ssl
RUN a2ensite default-ssl.conf
RUN a2dissite 000-default.conf
