global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
    monitor: 'codelab-monitor'

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:

  - job_name: 'app_node_exporter'
    static_configs:
     - targets: ['10.0.6.86:9100']
  
  - job_name: 'app_cadvisor'
    static_configs:
     - targets: ['10.0.6.86:8080']

  - job_name: 'ngnix_node_exporter'
    static_configs:
     - targets: ['10.0.4.188:9100']
  
  - job_name: 'ngnix_cadvisor'
    static_configs:
     - targets: ['10.0.4.188:8080']