version: '3'

volumes:
  certbot_www:
    driver: local
  certbot_certificets:
    driver: local

services:
  nginx:
    container_name: nginx
    build: 
      context: ./nginx
    volumes:
      - certbot_certificets:/etc/letsencrypt
      - certbot_www:/var/www/certbot
    ports: 
      - "443:443"
      - "80:80"
    restart: unless-stopped

  certbot:
    build: 
      context: ./certbot
    container_name: certbot
    volumes: 
      - certbot_certificets:/etc/letsencrypt
      - certbot_www:/var/www/certbot
    restart: unless-stopped