version: '3'

volumes:
  nextcloud-data:
    driver: local
  grafana-data:
    driver: local

services:

  nextcloud:
    environment:
      - NEXTCLOUD_ADMIN_USER=Admin
      - NEXTCLOUD_ADMIN_PASSWORD=Admin
    build: 
      context: ./nextcloud
    container_name: nextcloud
    ports: 
      - "8080:80"
    volumes:
      - nextcloud-data:/var/www/html/data
    restart: unless-stopped