version: '3'

volumes:
  nextcloud-data:
    driver: local
  nextcloud-config:
    driver: local
  nextcloud-instance:
    driver: local

services:

  nextcloud:
    environment:
      - NEXTCLOUD_ADMIN_USER=${NC_ADMIN_USER}
      - NEXTCLOUD_ADMIN_PASSWORD=${NC_ADMIN_PASSWORD}
      - SQLITE_DATABASE=db
      - PHP_MEMORY_LIMIT=${NC_PHP_MEMORY_LIMIT}
      - PHP_UPLOAD_LIMIT=${NC_PHP_UPLOAD_LIMIT}
      - NEXTCLOUD_TRUSTED_DOMAINS=${NC_TRUSTED_DOMAINS}
      - OVERWRITEWEBROOT=${NC_OVERWRITEWEBROOT}
      - OVERWRITEPROTOCOL=${NC_OVERWRITEPROTOCOL}
      - NC_DEFAULT_LOCALE=${NC_DEFAULT_LOCALE}
      - NC_DEFAULT_LANGUAGE=${NC_DEFAULT_LANGUAGE}
      - NC_DEFAULT_PHONE_REGION=${NC_DEFAULT_PHONE_REGION}
    build: 
      context: ./nextcloud
    container_name: nextcloud
    ports: 
      - "4000:80"
    volumes:
      - nextcloud-data:/var/www/html/data
      - nextcloud-config:/var/www/html/config
      - nextcloud-instance:/var/www/html
    restart: unless-stopped

  backup:
    environment:
      - BU_REMOTE_SERVER=${BU_REMOT_USER}@${BU_REMOTE_SERVER}
      - BU_REMOTE_PATH=${BU_REMOTE_PATH}
    build:
      context: ./backup
    container_name: backup
    volumes:
      - /home/debian/.ssh/id_rsa:/root/.ssh/id_rsa
      - nextcloud-data:/backup/data
      - nextcloud-config:/backup/config
      - nextcloud-instance:/backup/html
    restart: unless-stopped