version: '3'

volumes:
  nextcloud-data:
    driver: local
  nextcloud-config:
    driver: local
  nextcloud-instance:
    driver: local

services:

  nextcloud:
    environment:
      - NEXTCLOUD_ADMIN_USER=${NEXTCLOUD_ADMIN_USER}
      - NEXTCLOUD_ADMIN_PASSWORD=${NEXTCLOUD_ADMIN_PASSWORD}
      - SQLITE_DATABASE=db
      - NEXTCLOUD_TRUSTED_DOMAINS=${NEXTCLOUD_TRUSTED_DOMAINS}
    build: 
      context: ./nextcloud
    container_name: nextcloud
    ports: 
      - "80:4000"
    volumes:
      - nextcloud-data:/var/www/html/data
      - nextcloud-config:/var/www/html/config
      - nextcloud-instance:/var/www/html
    restart: unless-stopped